provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  pyadd:
    lang: python3
    handler: ./pyadd
    image: pyadd:latest
  pycho:
    lang: python3
    handler: ./pycho
    image: pycho:latest
